spring:
  datasource:
    url: 'jdbc:postgresql://localhost:5432/auction'
    username: ''
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  jwtSecret: JWTSuperSecretKey
  jwtExpiration: 9000000
