spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${SCHEMA_DB}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
app:
  jwtSecret: ${JWT_SECRET}
  jwtExpiration: ${JWT_EXPIRATION}
  emailUsername: ${EMAIL_USERNAME}
  emailPassword: ${EMAIL_PASSWORD}
  hostUrl: ${HOST_URL}
